### ISSUE TITLE
Warning - Update of sensor and alam panel take longer time than expected

### ISSUE THREAD

**Issue by baunan** [gjohansson-ST/sector#11]
Hi,
Using this application for my Norwegian subscription for Sector Alarm. Everything is working as expected, but in the log I get the warning that update of sensor and alarm panel takes longer than expected (see picture). Would be good if something could be done with it.

I am running on version 0.1.9 and HA core 112.2 and 3.13 of the operating system.
![image](https://user-images.githubusercontent.com/59838425/87319915-8cd09680-c52a-11ea-998b-21627a428bf0.png)

Bjorn

**Comment by gjohansson-ST** [comment]
Hi.
This is because the api of Sector Alarm is very slow and Home Assistant in itself has a 10 second limit to throw a warning as shown in your picture. There is no error in this, just how it's built and I can of course not speed up the api from Sector.
Unfortunately you have to just leave this ones as they are, they are safe to ignore.
Note that mostly it's the temp-sensors which are slow to update so using the config you can remove them if you wish.
